# Generated by Django 5.2.13 on 2026-04-15 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('idGuest', models.AutoField(primary_key=True, serialize=False)),
                ('namaGuest', models.CharField(max_length=50)),
                ('ktp', models.ImageField(max_length=255, upload_to='ktp/')),
                ('status', models.CharField(choices=[('Reguler', 'Reguler'), ('Member', 'Member')], default='Reguler', max_length=50)),
                ('nomorTelepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('nomorKamar', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('posisiLantai', models.IntegerField()),
                ('keteranganKondisi', models.CharField(max_length=255)),
                ('statusKamar', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terisi', 'Terisi'), ('Perawatan', 'Perawatan')], default='Tersedia', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipeGuest',
            fields=[
                ('idTipeGuest', models.AutoField(primary_key=True, serialize=False)),
                ('namaTipeGuest', models.CharField(max_length=50)),
                ('persenDiskon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipeKamar',
            fields=[
                ('idtipekamar', models.AutoField(primary_key=True, serialize=False)),
                ('namaTipekamar', models.CharField(max_length=50)),
                ('hargaKamar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fasilitas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('idPesan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPesan', models.DateField(auto_now=True)),
                ('tanggalCheckin', models.DateField()),
                ('tanggalCheckout', models.DateField()),
                ('diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('totalBayar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statusPembayaran', models.CharField(choices=[('Dibayar', 'Dibayar'), ('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Dibayar', max_length=50)),
                ('metodeBayar', models.CharField(choices=[('Transfer', 'Transfer'), ('Cash', 'Cash')], default='Transfer', max_length=50)),
                ('idGuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nomorKamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kamar', verbose_name='Kamar')),
                ('idPesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemesanan', verbose_name='Pemesanan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPembayaran',
            fields=[
                ('idDetailBayar', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahPembayaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buktiBayar', models.ImageField(upload_to='bukti_bayar/')),
                ('idPesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemesanan', verbose_name='Pemesanan')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='idTipeGuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipeguest', verbose_name='Tipe Guest'),
        ),
        migrations.AddField(
            model_name='kamar',
            name='idTipeKamar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipekamar'),
        ),
    ]
