# Generated by Django 5.2.13 on 2026-04-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detailpemesanan_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='idPesan',
        ),
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='nomorKamar',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='idTipeGuest',
        ),
        migrations.RemoveField(
            model_name='pemesanan',
            name='idGuest',
        ),
        migrations.RemoveField(
            model_name='kamar',
            name='idTipeKamar',
        ),
        migrations.DeleteModel(
            name='DetailPembayaran',
        ),
        migrations.DeleteModel(
            name='DetailPemesanan',
        ),
        migrations.DeleteModel(
            name='TipeGuest',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Pemesanan',
        ),
        migrations.DeleteModel(
            name='Kamar',
        ),
        migrations.DeleteModel(
            name='TipeKamar',
        ),
    ]
