# Generated by Django 5.2.13 on 2026-04-15 11:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('kamar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idPesan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPesan', models.DateField(auto_now=True)),
                ('tanggalCheckin', models.DateField()),
                ('tanggalCheckout', models.DateField()),
                ('diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('totalBayar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('statusPembayaran', models.CharField(choices=[('Dibayar', 'Dibayar'), ('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=50)),
                ('metodeBayar', models.CharField(choices=[('Transfer', 'Transfer'), ('Cash', 'Cash')], default='Transfer', max_length=50)),
                ('idGuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('subTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nomorKamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamar.kamar', verbose_name='Kamar')),
                ('idPesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan.pemesanan', verbose_name='Pemesanan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
