# Generated by Django 5.2.13 on 2026-04-15 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipeGuest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idTipeGuest', models.AutoField(primary_key=True, serialize=False)),
                ('namaTipeGuest', models.CharField(max_length=50)),
                ('persenDiskon', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idGuest', models.AutoField(primary_key=True, serialize=False)),
                ('namaGuest', models.CharField(max_length=50)),
                ('ktp', models.ImageField(max_length=255, upload_to='ktp/')),
                ('status', models.CharField(choices=[('Reguler', 'Reguler'), ('Member', 'Member')], default='Reguler', max_length=50)),
                ('nomorTelepon', models.CharField(max_length=20)),
                ('idTipeGuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.tipeguest', verbose_name='Tipe Guest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
