# Generated by Django 5.2.13 on 2026-04-15 11:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPembayaran',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idDetailBayar', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahPembayaran', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('buktiBayar', models.ImageField(upload_to='bukti_bayar/')),
                ('idPesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan.pemesanan', verbose_name='Pemesanan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
