# Generated by Django 5.2.13 on 2026-04-15 11:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipeKamar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idtipekamar', models.AutoField(primary_key=True, serialize=False)),
                ('namaTipekamar', models.CharField(max_length=50)),
                ('hargaKamar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fasilitas', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomorKamar', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('posisiLantai', models.IntegerField()),
                ('keteranganKondisi', models.CharField(max_length=255)),
                ('statusKamar', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terisi', 'Terisi'), ('Perawatan', 'Perawatan')], default='Tersedia', max_length=50)),
                ('idTipeKamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamar.tipekamar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
